# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('keyword', models.CharField(help_text='\u7528\u6237\u53d1\u51fa\u7684\u5173\u952e\u8bcd', max_length=256, primary_key=True, serialize=False, verbose_name='\u5173\u952e\u8bcd')),
                ('content', models.TextField(blank=True, help_text='\u56de\u590d\u7ed9\u7528\u6237\u7684\u5185\u5bb9', null=True, verbose_name='\u5185\u5bb9')),
                ('reply_type', models.CharField(choices=[('1', '\u6587\u5b57\u56de\u590d'), ('2', '\u56fe\u6587\u56de\u590d')], default='1', max_length=1, verbose_name='\u56de\u590d\u7c7b\u578b')),
                ('to_url', models.URLField(null=True, verbose_name='\u8df3\u8f6c\u94fe\u63a5')),
                ('pic_url', models.URLField(null=True, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5173\u952e\u8bcd',
                'verbose_name_plural': '\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='Wechat_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('access_token_expires_at', models.CharField(max_length=20)),
                ('get_date', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
